language: scala
  
jdk: oraclejdk8

scala:
  - 2.13.1

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.coursier

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
