package pl.msitko.terraform4s.codegen.comments

import java.time.Instant

object FileLevelCommentCodegen {

  def generate(timestamp: Instant, providerName: String, providerVersion: Option[String]): String =
    s"""/**
       |  * This file has been generated by terraform4s at $timestamp
       |  * Provider name: $providerName
       |  * Provider version: ${providerVersion.getOrElse("unknown")}
       |  */
       |
       |""".stripMargin
}
