package pl.msitko.terraform4s.codegen.comments

import java.time.Instant

object FileLevelCommentCodegen {

  def generate(
      timestamp: Instant,
      terraformVersion: String,
      providerName: String,
      providerVersion: Option[String]): String =
    s"""/**
       |  * This file has been generated by terraform4s at $timestamp
       |  * Terraform version: $terraformVersion
       |  * Provider name: $providerName
       |  * Provider version: ${providerVersion.getOrElse("unknown")}
       |  */
       |""".stripMargin
}
